# Generated by Django 4.2.1 on 2023-07-07 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import petstagram_workshop.photos.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('personal_photo', models.ImageField(upload_to='media/', validators=[petstagram_workshop.photos.validators.validate_file_size])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
