# Generated by Django 4.2.1 on 2023-07-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_personal_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='pet',
            name='type',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
